version: 2
jobs:
  build:
    machine:
       image: ubuntu-1604:201903-01
    steps:
      - run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - run: echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV && echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
      - run: nvm install 8
      - checkout
      # Get Java dependencies before trying to build tests.
      - run: mvn dependency:go-offline
      # Installs @percy/agent
      - run: npm install
      - run: npm test
      - checkout
      # Get Java dependencies before trying to build tests.
      - run: mvn dependency:go-offline
      # Installs @percy/agent
      - run: npm install
      - run: npm test