version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - run: mvn dependency:go-offline
    - run: 
        name: mvn package
        command: |
                mvn package
    - run: 
        name: Correr programa
        command: |
                mvn -Dtest=com.godiva.test.Header clean test
workflows:
  version: 2
  workflow:
    jobs:
    - build