version: 2
jobs:
  build:
    machine:
       image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install -U selenium
      - run: sudo apt-get install nginx
      - run: sudo cp ./selenium-tutorial-main.html /var/www/html/selenium-tutorial-main.html
      - run:
          name: Download Selenium
          command: |
            python test/Qxf2_Tutorial_BrowserStack_Test.py
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run: wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
          # Unzip the browserstack binary file
      - run: unzip BrowserStackLocal-linux-x64.zip
          # Run the file with your access key
          - ./BrowserStackLocal $BROWSERSTACK KEY:
              background: true