version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/prueba-03/BrowserTesting
    steps:
    - checkout
    - run: mvn dependency:go-offline
    - run: mvn package
    - run: mvn clean compile exec:java
workflows:
  version: 2
  workflow:
    jobs:
    - build