version: 2
jobs:
  build:
    machine:
       image: ubuntu-1604:201903-01
       image: circleci/python:jessie-node-browsers
    steps:
       - checkout
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run: 
          command: python tests/test_selenium.py