version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/prueba-03/BrowserTesting
    steps:
    - checkout
    - restore_cache:
        key: prueba-03/BrowserTesting-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: prueba03/BrowserTesting-{{ checksum "pom.xml" }}
    - run: mvn package
    - run: mvn clean compile exec:java
workflows:
  version: 2
  workflow:
    jobs:
    - build