version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - checkout
    - restore_cache:
        key: prueba-03-{{ checksum "pom.xml" }}
    - run: 
        name: mvm
        command: |
            mvn dependency:go-offline
            mvn package
    - run: 
        name: correr
        command: |
            mvn -Dtest=com.godiva.test.Header clean test