version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      working_directory: ~/prueba-03
    steps:
    - checkout
    - restore_cache:
        key: prueba-03-{{ checksum "test/Automation/pom.xml" }}
    - run: mvn dependency:go-offline
    - run: 
        name: mvm package
        command: |
            mvn package
    - run: 
        name: correr
        command: |
            cd test/Automationsrc/test/java/com/godiva/test
            mvn clean test
workflows:
  version: 2
  workflow:
    jobs:
    - build