version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/prueba-03
    steps:
    - checkout
    - restore_cache:
        key: prueba-03-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: prueba-03-{{ checksum "pom.xml" }}
    - run: 
        name: mvn package
        command: |
                mvn package
    - run: 
        name: Correr programa
        command: |
                mvn clean compile exec:java
workflows:
  version: 2
  workflow:
    jobs:
    - build