version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/prueba-03/test/Automation
    steps:
    - checkout
    - restore_cache:
        key: Automation-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - run: 
        name: correr
        command: |
            mvn package
    - run: 
        name: correr
        command: |
            mvn -Dtest=com.godiva.test.Header clean test
workflows:
  version: 2
  workflow:
    jobs:
    - build